import Head from 'next/head';
import Image from 'next/image';
import photo from '@images/photo3.jpg';
import CardHabilities from '@components/CardHabilities';

//import images
import reactIcon from '@images/react-icon.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>{`Erick's Project Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet"></link>
      </Head>

      <main className="w-full min-h-screen bg-slate-200 pb-12">
        <div className="flex flex-col items-center p-12 pt-20 gap-2 font-Roboto border-b border-slate-500 rounded-2xl shadow-[0_-35px_60px_15px_rgba(0,0,0,0.7)]">
          <div className="flex max-w-[200px] rounded-lg relative overflow-hidden shadow-[0_35px_60px\15px_rgba(170,170,170,0.3)]">
            <Image src={photo} width="300px" height="460px" />
          </div>
          <div className="flex flex-col items-center mt-2">
            <h2 className="m-0 p-0 font-semibold text-lg">Erick Antonio Rodríguez Son</h2>
            <span>Desarrollador WEB FullStack</span>
          </div>
        </div>
        <div className="flex flex-col items-center  gap-5">
          <div className="p-2 pt-8 w-max flex flex-col items-center border-b border-emerald-500">
            <h3 className="font-semibold text-lg">Servicios</h3>
            <span>¿Qué puedo hacer?</span>
          </div>
          <div className="flex justify-center flex-wrap p-4 font-Roboto">
            <CardHabilities
              image={reactIcon}
              hability="React JS"
              description="Construir interfaces de usuario para aplicaciones web escalables con React.js. Integrar React a una aplicación existente para mejorarla."
              animate={{ rotate: 360 }}
              initial={{ rotate: 0 }}
              transition={{ repeat: Infinity, duration: 5, delay: 0.2, ease: 'linear' }}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
